name: Set Community Label

on:
  issues:
    types: [opened]

jobs:
  set-community-label:
    name: Set Community Label
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'opened'
        uses: jamessingleton/is-organization-member@1.0.1
        with:
          organization: <your-organization-name>
          username: ${{ github.event.issue.user.login }}
          token: <your-github-token>
      - name: Set Community Label If Needed
        if: ${{steps.is_organization_member.outputs.result == 'false'}}
        uses: andymckay/labeler@master
        with:
          add-labels: "community"
